### ISSUE TITLE
Virtioqueue split error on 'large' tcp packets

### ISSUE THREAD

**Issue by CarlWachter** [hermitcore/hermit-playground#32]
Using kernel version https://github.com/hermit-os/kernel/tree/cbcf65a591eed712c8dd12af24cebd7f73882be1

When sending data above ca. 1000 bytes, after ca. 50 transmissions the following error will come up:
```bash
[0] [PANIC] panicked at src/virtio/virtqueue/split.rs:259:18:
The buff_id is incorrect or the reference to the TransferToken was misplaced.
```

**Comment by mkroening** [comment]
This sounds like https://github.com/hermit-os/kernel/issues/1327, which got fixed by https://github.com/hermit-os/kernel/pull/1329.

Does this still happen with latest `main`?

**Comment by CarlWachter** [comment]
It works with latest `main`. Thanks!
